### ISSUE TITLE
Memory consumption increases on windows after file upload/import

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#21]
This issue repoduced on the 
http://repo.enonic.com/public/com/enonic/xp/distro/6.12.0-B1/
The issue reproducing when create new content  via the **com.enonic.xp.content.ContentService** as well

1.  start the application an open Content Studio
2.  upload SVG  file 
**BUG**
-icon for the content and notification message does not appear
- when click on the uploaded svg, error appears:
PreviewContentHandler.ts:65 Uncaught TypeError: Cannot read property 'getModel' of undefined
    at PreviewContentHandler.ts:65
    at Array.map (<anonymous>)
    at PreviewContentHandler.makeRenderableRequests (PreviewContentHandler.ts:64)
    at PreviewContentHandler.getRenderablePromise (PreviewContentHandler.ts:37)
    at PreviewContentHandler.updateState (PreviewContentHandler.ts:33)
    at ContentTreeGridActions.updateActionsEnabledState (ContentTreeGridActions.ts:63)
    at ContentBrowsePanel.BrowsePanel.onHighlightingChanged (BrowsePanel.ts:147)
    at ContentBrowsePanel.<anonymous> (BrowsePanel.ts:81)
    at later (AppHelper.ts:17)

-**And Memory Usage has been increased in 3 times**

![java](https://user-images.githubusercontent.com/3728712/30544591-ab5a8f5a-9c8f-11e7-91b6-c48d77fa4daa.png)

**SERVER-log**
16:10:53.666 WARN  c.e.x.e.impl.ExtractorResultFactory - Error cleaning up extracted text
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:472)
	at java.lang.StringBuffer.append(StringBuffer.java:310)
	at java.lang.StringBuffer.append(StringBuffer.java:97)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:486)
	at java.lang.StringBuffer.append(StringBuffer.java:338)
	at java.util.regex.Matcher.appendReplacement(Matcher.java:890)
	at java.util.regex.Matcher.replaceAll(Matcher.java:955)
	at java.lang.String.replaceAll(String.java:2223)
	at com.enonic.xp.extractor.impl.ExtractedTextCleaner.cleanLineBreaks(ExtractedTextCleaner.java:51)
	at com.enonic.xp.extractor.impl.ExtractedTextCleaner.clean(ExtractedTextCleaner.java:36)
	at com.enonic.xp.extractor.impl.ExtractorResultFactory.create(ExtractorResultFactory.java:25)
	at com.enonic.xp.extractor.impl.BinaryExtractorImpl.extract(BinaryExtractorImpl.java:54)
	at com.enonic.xp.core.impl.media.MediaInfoServiceImpl.parseMediaInfo(MediaInfoServiceImpl.java:34)
	at com.enonic.xp.core.impl.content.CreateMediaCommand.doExecute(CreateMediaCommand.java:42)
	at com.enonic.xp.core.impl.content.CreateMediaCommand.execute(CreateMediaCommand.java:37)
	at com.enonic.xp.core.impl.content.ContentServiceImpl.create(ContentServiceImpl.java:263)
	at com.enonic.xp.admin.impl.rest.resource.content.ContentResource.createMedia(ContentResource.java:287)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220)
	at com.enonic.xp.jaxrs.impl.JaxRsServlet.service(JaxRsServlet.java:46)

**Comment by jsi** [comment]
Here is a link to the SVG file Siarhei used: https://drive.google.com/open?id=0B1UYNmM2ondZYkludlZmRTRyTDQ
